// src/firebase/config.ts

// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README to configure your Firebase project.
// This configuration is used to initialize the Firebase app.

// IMPORTANT: This is a public configuration.
// For security reasons, do not expose any sensitive information here.
// Security is enforced by Firebase Security Rules.

import { FirebaseOptions } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_API_KEY`');
  }
  if (!firebaseConfig.authDomain) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN`');
  }
  if (!firebaseConfig.projectId) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_PROJECT_ID`');
  }
  if (!firebaseConfig.storageBucket) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET`');
  }
  if (!firebaseConfig.messagingSenderId) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID`');
  }
  if (!firebaseConfig.appId) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_APP_ID`');
  }
  return firebaseConfig;
}
