// src/firebase/config.ts

// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README to configure your Firebase project.
// This configuration is used to initialize the Firebase app.

// IMPORTANT: This is a public configuration.
// For security reasons, do not expose any sensitive information here.
// Security is enforced by Firebase Security Rules.

import { FirebaseOptions } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyA-HnBbPf8R6qolIH_Qm9PbECrUKSi4Db8",
  authDomain: "ampire-studio-92664092-32a02.firebaseapp.com",
  projectId: "ampire-studio-92664092-32a02",
  storageBucket: "ampire-studio-92664092-32a02.appspot.com",
  messagingSenderId: "156171619491",
  appId: "1:156171619491:web:6d2cce1f3ad042d82a4316",
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing Firebase config: `apiKey`');
  }
  if (!firebaseConfig.authDomain) {
    throw new Error('Missing Firebase config: `authDomain`');
  }
  if (!firebaseConfig.projectId) {
    throw new Error('Missing Firebase config: `projectId`');
  }
  if (!firebaseConfig.storageBucket) {
    throw new Error('Missing Firebase config: `storageBucket`');
  }
  if (!firebaseConfig.messagingSenderId) {
    throw new Error('Missing Firebase config: `messagingSenderId`');
  }
  if (!firebaseConfig.appId) {
    throw new Error('Missing Firebase config: `appId`');
  }
  return firebaseConfig;
}
